### ISSUE TITLE
more generic approach; another use case

### ISSUE THREAD

**Issue by ghost** [RachitBansal/RedditFlairDetector#2]
Hi,

Hope you are all well !

I just wanted to ask you if your approach could apply to classify arxiv abstracts into specific categories/tasks ?

More precisely, I have a dataset of 90k abstracts classified in tasks.
https://paper2code.com/public/tag_predict.txt.tar.gz

How can I train a model based on this dataset ?

Cheers,
X

**Comment by RachitBansal** [comment]
Hi @x0rzkov,

Please check out the [Notebook for Deep Learning techniques](https://github.com/RachitBansal/RedditFlairDetector/blob/master/3_Modelling_DL.ipynb). It should be very straightforward to adapt that code to your data. If you want, you can directly open the notebook in Colab, upload your data to the Drive, mount Drive in the Colab notebook and use the code. 

You'll just have to ensure that the data format remains the same as shown in the notebook, especially for the BERT-based models in the end. They require a specific format as shown there. 

Let me know if you face any difficulties. I will be happy to help.
